config/routes.rb
Rottenpotatoes::Application.routes.draw do
  # map '/' to be a redirect to '/movies'
  get 'movies/search_tmdb', to: 'movies#search_tmdb', as: 'search_tmdb'
  post '/add_movie', to: 'movies#add_movie', as: 'add_movie'

  resources :movies

  root to: redirect('/movies')
end

app/models/movie.rb
class Movie < ActiveRecord::Base
  def self.find_in_tmdb(search_params, api_key = '031cf0ed8d1e80fcb253105cb20c7598')
    search_query = search_params[:title] || search_params[:search_terms]
    
    return nil if search_query.blank?

    url = "https://api.themoviedb.org/3/search/movie?api_key=#{api_key}&query=#{URI.encode_www_form_component(search_query)}"
    
    url += "&year=#{search_params[:release_year]}" unless search_params[:release_year].blank?
    url += "&language=#{search_params[:language]}" unless search_params[:language].blank?

    response = Faraday.get(url)
    data = JSON.parse(response.body)

    return [] if data["results"].blank?

    data["results"].map do |movie|
      Movie.new(
        title: movie["title"],
        release_date: movie["release_date"],
        rating: "R",
        description: movie["overview"]
      )
    end
  end

  def self.all_ratings
    %w[G PG PG-13 R]
  end

  def self.with_ratings(ratings, sort_by)
    if ratings.nil? || ratings.empty?
      all.order sort_by
    else
      where(rating: ratings.map(&:upcase)).order sort_by
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  before_action :force_index_redirect, only: [:index]

  def show
    id = params[:id]
    @movie = Movie.find(id)
  end

  def index
    @all_ratings = Movie.all_ratings
    @movies = Movie.with_ratings(ratings_list, sort_by)
    @ratings_to_show_hash = ratings_hash
    @sort_by = sort_by
    session['ratings'] = ratings_list
    session['sort_by'] = @sort_by
  end

  def new
  end

  def create
    @movie = Movie.create!(movie_params)
    flash[:notice] = "#{@movie.title} was successfully created."
    redirect_to movies_path
  end

  def edit
    @movie = Movie.find params[:id]
  end

  def update
    @movie = Movie.find params[:id]
    @movie.update!(movie_params)
    flash[:notice] = "#{@movie.title} was successfully updated."
    redirect_to movie_path(@movie)
  end

  def destroy
    @movie = Movie.find(params[:id])
    @movie.destroy
    flash[:notice] = "Movie '#{@movie.title}' deleted."
    redirect_to movies_path
  end

  def search_tmdb
    if params[:commit] 
      if params[:title].blank?
        flash.now[:warning] = "Please fill in all required fields!"
      else
        @movies = Movie.find_in_tmdb(params)
        if @movies.blank?
          flash.now[:warning] = 'No movies found with given parameters!'
        end
      end
    end
    render :search_tmdb
  end

  def add_movie
    movie = Movie.create!(add_movie_params)
    flash[:success] = "#{movie.title} was successfully added to RottenPotatoes."
    redirect_to search_tmdb_path
  end

  private

  def movie_params
    params.require(:movie).permit(:title, :rating, :release_date, :description)
  end

  def add_movie_params
    params.permit(:title, :release_date, :rating, :description)
  end

  def force_index_redirect
    return unless !params.key?(:ratings) || !params.key?(:sort_by)
    flash.keep
    url = movies_path(sort_by: sort_by, ratings: ratings_hash)
    redirect_to url
  end

  def ratings_list
    params[:ratings]&.keys || session[:ratings] || Movie.all_ratings
  end

  def ratings_hash
    ratings_list.to_h { |item| [item, "1"] }
  end

  def sort_by
    params[:sort_by] || session[:sort_by] || 'id'
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/movies_helper.rb
module MoviesHelper
  # Checks if a number is odd:
  def oddness(count)
    count.odd? ? "odd" : "even"
  end
end

app/views/layouts/_flash.erb
<% if flash[:notice] %>
  <div class="alert alert-info" role="alert" id="notice">
    <%= flash[:notice] %>
  </div>
<% elsif flash[:warning] %>
  <div class="alert alert-danger" role="alert" id="warning">
    <%= flash[:warning] %>
  </div>
<% end %>

app/views/layouts/application.html.erb
<%# Our "base" layout should be a valid HTML document. %>
<!DOCTYPE html>
<html>
  <head>
    <title>Rotten Potatoes!</title>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" integrity="sha384-JcKb8q3iqJ61gNV9KGb8thSsNjpSL0n8PARn9HuZOnIxN0hoP+VmmDGMN5t9UJ0Z" crossorigin="anonymous">
    <%= stylesheet_link_tag 'application', 'media' => 'all' %>
    <%= javascript_include_tag 'application' %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <%# These classes come from the Bootstrap CSS framework. %>
    <nav class="navbar navbar-expand-lg bg-primary text-white mb-3">
      <h1 class="title">Rotten Potatoes!</h1>
    </nav>
    <div class="container">
      <main id="main">
        <%= yield %>
      </main>
    </div>
  </body>
</html>

app/views/movies/edit.html.erb
<h2>Edit Existing Movie</h2>
<%= form_tag movie_path(@movie), :method => :put do %>
  <%= label :movie, :title, 'Title', class: 'col-form-label' %>
  <%= text_field :movie, 'title', class: 'form-control' %>
  <%= label :movie, :rating, 'Rating', class: 'col-form-label'  %>
  <%= select :movie, :rating, ['G','PG','PG-13','R'], {}, {class: 'form-control col-1'} %>
  <%= label :movie, :release_date, 'Released On', class: 'col-form-label'  %>
  <%= date_select :movie, :release_date, {}, class: 'form-control col-2 d-inline' %>
  <br/>
  <%= submit_tag 'Update Movie Info', class: 'btn btn-primary' %>
  <%= link_to 'Cancel', movies_path, class: 'btn btn-secondary' %>
<% end %>

app/views/movies/index.html.erb
<!--  This file is app/views/movies/index.html.erb -->
<h2>All Movies</h2>

<div class="row navigation">
  <div class="col-md-10">
    <%= form_tag movies_path, method: :get, id: 'ratings_form' do %>
      <%= hidden_field_tag 'sort_by', @sort_by %>
      Include:
      <% @all_ratings.each do |rating| %>
        <div class="form-check  form-check-inline">
          <%= label_tag "ratings[#{rating}]", rating, class: 'form-check-label' %>
          <%= check_box_tag "ratings[#{rating}]", '1', (@ratings_to_show_hash.include?(rating)), class: 'form-check-input' %>
        </div>
      <% end %>
      <%= submit_tag 'Refresh', id: 'ratings_submit', class: 'btn btn-primary' %>
    <% end %>
  </div>
  <div class="col-md-2">
    <%= link_to 'Search TMDb', search_tmdb_path, class: 'btn btn-warning' %>
  </div>
</div>

<table class="table table-striped col-md-12" id="movies">
  <thead>
    <tr>
      <th>
        <%= link_to 'Movie Title', movies_path({sort_by: 'title', ratings: @ratings_to_show_hash}),
                      id: 'title_header', class: ('bg-warning hilite' if @sort_by == 'title') %>
      </th>
      <th>Rating</th>
      <th>
        <%= link_to 'Release Date',
              movies_path({sort_by: 'release_date', ratings: @ratings_to_show_hash}),
              id: 'release_date_header', class: ('bg-warning hilite' if @sort_by == 'release_date') %>
      </th>
      <th>More Info</th>
    </tr>
  </thead>
  <tbody>
    <% @movies.each do |movie| %>
      <tr>
        <td>
          <%= movie.title %>
        </td>
        <td>
          <%= movie.rating %>
        </td>
        <td>
          <%= movie.release_date %>
        </td>
        <td>
          <%= link_to "More about #{movie.title}", movie_path(movie) %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Add new movie', new_movie_path, class: 'btn btn-primary' %>

app/views/movies/new.html.erb
<h2>Create New Movie</h2>

<%= form_tag movies_path, class: 'form' do %>
  <%= label :movie, :title, 'Title', class: 'col-form-label' %>
  <%= text_field :movie, :title, class: 'form-control' %>
  <%= label :movie, :rating, 'Rating', class: 'col-form-label' %>
  <%= select :movie, :rating, ['G','PG','PG-13','R'], {}, {class: 'form-control col-1'} %>
  <%= label :movie, :release_date, 'Released On', class: 'col-form-label' %>
  <%= date_select :movie, :release_date, {}, class: 'form-control col-2 d-inline' %>
  <br/>
  <%= submit_tag 'Save Changes', class: 'btn btn-primary' %>
  <%= link_to 'Cancel', movies_path, class: 'btn btn-secondary' %>
<% end %>

app/views/movies/search_tmdb.html.erb
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

<h2>Search in TMDb</h2>

<% flash.each do |key, value| %>
  <div class="alert alert-<%= key %> alert-dismissible fade show" role="alert">
    <%= value %>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

<div class="search-container mb-4">
  <%= form_tag(search_tmdb_path, method: :get, id: 'tmdb_form') do %>
    <div class="mb-3">
      <label for="movie_title_field" class="form-label">Movie Name (required)</label>
      <%= text_field_tag 'title', params[:title], class: "form-control", id: "movie_title_field", placeholder: "Manhunter" %>
    </div>

    <div class="mb-3">
      <label for="movie_year_field" class="form-label">Release Year (optional)</label>
      <%= text_field_tag 'release_year', params[:release_year], class: "form-control", id: "movie_year_field", placeholder: "1986" %>
    </div>

    <div class="mb-3">
      <div class="form-check form-check-inline">
        <%= radio_button_tag 'language', 'en', params[:language] == 'en', class: "form-check-input", id: "language_en" %>
        <label class="form-check-label" for="language_en">English Only</label>
      </div>
      <div class="form-check form-check-inline">
        <%= radio_button_tag 'language', 'all', params[:language] != 'en', class: "form-check-input", id: "language_all" %>
        <label class="form-check-label" for="language_all">All Languages</label>
      </div>
    </div>

    <div class="mt-3">
      <%= submit_tag 'Search', id: 'tmdb_submit', class: 'btn btn-warning' %>
    </div>
  <% end %>
</div>

<%# This table for results remains the same %>
<% if @movies && @movies.any? %>
  <table id="search_movies" class="table table-striped">
    <thead>
      <tr>
        <th>Title</th>
        <th>Release Date</th>
        <th>Description</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <% @movies.each do |movie| %>
        <tr>
          <td><%= movie.title %></td>
          <td><%= movie.release_date %></td>
          <td><%= movie.description %></td>
          <td>
            <%= form_tag add_movie_path, method: :post do %>
              <%= hidden_field_tag :title, movie.title %>
              <%= hidden_field_tag :release_date, movie.release_date %>
              <%= hidden_field_tag :rating, movie.rating %>
              <%= hidden_field_tag :description, movie.description %>
              <%= submit_tag "Add Movie", class: "btn btn-primary" %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

<%= link_to 'Back to Home', movies_path, class: 'btn btn-primary mt-3' %>

app/views/movies/show.html.erb
<!--  app/views/movies/show.html.erb -->
<h2>Details about <em><%= @movie.title %></em></h2>

<ul id="details">
  <li>
    Rating:
    <%= @movie.rating %>
  </li>
  <li>
    Released on:
    <%= @movie.release_date.strftime("%B %d, %Y") %>
  </li>
</ul>

<h3>Description:</h3>
<p id="description">
  <%= @movie.description %>
</p>

<div class="row">
  <%= link_to 'Edit', edit_movie_path(@movie), class: 'btn btn-primary col-2' %>
  <%= link_to 'Delete', movie_path(@movie), 'data-method': 'delete', 'data-confirm': 'Are you sure?', class: 'btn btn-danger col-2' %>
  <%= link_to 'Back to movie list', movies_path, class: 'btn btn-primary col-2' %>
</div>